;; color theme
(require 'color-theme)
(color-theme-initialize)

(color-theme-charcoal-black)
;(color-theme-blippblopp)
;(color-theme-billw)
;(color-theme-inkpot)
;(load-file "~/.emacs.d/vendor/color-theme/color-theme-tango-2.el")
;(color-theme-tango-2)
;(load-file "~/.emacs.d/vendor/color-theme/twilight-emacs/color-theme-twilight.el")
;(color-theme-twilight)
;(color-theme-montz)
;(load-file "~/.emacs.d/vendor/color-theme/zenburn.el")
;(color-theme-zenburn)
;(load-file "~/.emacs.d/vendor/color-theme/color-theme-blackboard.el")
;(color-theme-blackboard)
;(load-file "~/.emacs.d/vendor/color-theme/color-theme-hober2.el")
;(color-theme-hober2)